# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudstic < Formula
  desc "Content-addressable, encrypted backup tool for Google Drive, OneDrive, and local files"
  homepage "https://github.com/cloudstic/cli"
  version "1.10.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cloudstic/cli/releases/download/v1.10.0/cloudstic_1.10.0_darwin_amd64.tar.gz"
      sha256 "d122454d9aa04d0552bc15048e238a9a94e71497611acfa321e3572fa55d78ec"

      define_method(:install) do
        bin.install "cloudstic"
        generate_completions_from_executable(bin/"cloudstic", "completion")
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cloudstic/cli/releases/download/v1.10.0/cloudstic_1.10.0_darwin_arm64.tar.gz"
      sha256 "d58c36d2e5d20d470f23ebf96b33b5d33d2a423fda25dd22b431362a4785e00d"

      define_method(:install) do
        bin.install "cloudstic"
        generate_completions_from_executable(bin/"cloudstic", "completion")
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudstic/cli/releases/download/v1.10.0/cloudstic_1.10.0_linux_amd64.tar.gz"
      sha256 "251dae029db8f624dbaf881c7e6082a2001f1e669fab18d46938efbe733cd93e"
      define_method(:install) do
        bin.install "cloudstic"
        generate_completions_from_executable(bin/"cloudstic", "completion")
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudstic/cli/releases/download/v1.10.0/cloudstic_1.10.0_linux_arm64.tar.gz"
      sha256 "c2b56a9b99a4c5dd04c9f46e257744b31712f47adbab7d6aec8266498a5582fa"
      define_method(:install) do
        bin.install "cloudstic"
        generate_completions_from_executable(bin/"cloudstic", "completion")
      end
    end
  end

  test do
    system "#{bin}/cloudstic", "version"
  end
end
