# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudstic < Formula
  desc "Content-addressable, encrypted backup tool for Google Drive, OneDrive, and local files"
  homepage "https://github.com/cloudstic/cli"
  version "1.0.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cloudstic/cli/releases/download/v1.0.6/cloudstic_1.0.6_darwin_amd64.tar.gz"
      sha256 "23953c8655d4a1bd419061d1fae86852d47ba6b764d13b52e12c87a5db1f9495"

      define_method(:install) do
        bin.install "cloudstic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cloudstic/cli/releases/download/v1.0.6/cloudstic_1.0.6_darwin_arm64.tar.gz"
      sha256 "71bb3f1adb934a38a66ce84cec1d8b9c06cfdfe9a1aecbd14f16c9adf613de78"

      define_method(:install) do
        bin.install "cloudstic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudstic/cli/releases/download/v1.0.6/cloudstic_1.0.6_linux_amd64.tar.gz"
      sha256 "84040d2b84d895b8808e600cd7d1adb946dc3451f386c8706171821d1e737b11"
      define_method(:install) do
        bin.install "cloudstic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudstic/cli/releases/download/v1.0.6/cloudstic_1.0.6_linux_arm64.tar.gz"
      sha256 "075551c47eb1ba75bfe341a67de0777065a3af9af83a1619336a7bc4fd6eedb3"
      define_method(:install) do
        bin.install "cloudstic"
      end
    end
  end

  test do
    system "#{bin}/cloudstic", "version"
  end
end
