# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Cloudstic < Formula
  desc "Content-addressable, encrypted backup tool for Google Drive, OneDrive, and local files"
  homepage "https://github.com/cloudstic/cli"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Cloudstic/cli/releases/download/v1.3.0/cloudstic_1.3.0_darwin_amd64.tar.gz"
      sha256 "b1f706f9eb1a5619eb266fe256152fbea24c3a5c36f93a3582ce012fe998b92f"

      define_method(:install) do
        bin.install "cloudstic"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Cloudstic/cli/releases/download/v1.3.0/cloudstic_1.3.0_darwin_arm64.tar.gz"
      sha256 "ed4ecaeffd79e212174902b86de0722a4eec74462a851812445c0887d4aa0c7e"

      define_method(:install) do
        bin.install "cloudstic"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudstic/cli/releases/download/v1.3.0/cloudstic_1.3.0_linux_amd64.tar.gz"
      sha256 "d0ee0d85651d7a52507efae2596abe023798570e35fa04989e096d543ef12791"
      define_method(:install) do
        bin.install "cloudstic"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Cloudstic/cli/releases/download/v1.3.0/cloudstic_1.3.0_linux_arm64.tar.gz"
      sha256 "3ed966cba47a457beb580ffb676e7f8646131f129d3cc7fe56d4ba7022d8650e"
      define_method(:install) do
        bin.install "cloudstic"
      end
    end
  end

  test do
    system "#{bin}/cloudstic", "version"
  end
end
