# This file was generated by GoReleaser. DO NOT EDIT.
cask "cloudstic" do
  name "cloudstic"
  desc "Content-addressable, encrypted backup tool for Google Drive, OneDrive, and local files"
  homepage "https://github.com/cloudstic/cli"
  version "1.0.2"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "cloudstic"

  on_macos do
    on_intel do
      url "https://github.com/Cloudstic/cli/releases/download/v#{version}/cloudstic_#{version}_darwin_amd64.tar.gz"
      sha256 "57d593f31ca765680246ce14e9d83e7492f61d9bf3a82ad78e7d849fbc8ba7bf"
    end
    on_arm do
      url "https://github.com/Cloudstic/cli/releases/download/v#{version}/cloudstic_#{version}_darwin_arm64.tar.gz"
      sha256 "39084e25c45a61bd0126d53a36e6e744409e63fd9bf0cbc6f450ac09e84a066b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/Cloudstic/cli/releases/download/v#{version}/cloudstic_#{version}_linux_amd64.tar.gz"
      sha256 "76012771545132a66b9d7ed605a2898061f8d6472c4a496367242476304e7965"
    end
    on_arm do
      url "https://github.com/Cloudstic/cli/releases/download/v#{version}/cloudstic_#{version}_linux_arm64.tar.gz"
      sha256 "9e5f98c6656bb0f39722b6b654d19a65cf7af6ab290d6f693cca48689b098d06"
    end
  end

  # No zap stanza required
end
